// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type WebVitalsMetric struct {
	Name  string `json:"name"`
	Value string `json:"value"`
}

type WebVitalsMetricCreateInput struct {
	Name  string `json:"name"`
	Value string `json:"value"`
}
